### ISSUE TITLE
Reversed points

### ISSUE THREAD

**Issue by Raffa87** [tu-rbo/turbo-ros-pkg#1]
Hi!
I am trying to use the Selected Points Publish, but it seems that points are in someway roto-translated
Thanks!

**Comment by roberto-martinmartin** [comment]
Hi Raffa,

I think the problem is that the selected points are republished using as 
"frame_id" for the point cloud the "fixed frame" you select in RVIZ. The 
right thing to do would be to use the same "frame_id" the original point 
cloud is defined in, but it is too complicated to obtain this 
information from within our plugin (we work with points, not with entire 
point clouds, and points do not contain "frame_id" information).

To avoid the problem you could try to select as "fixed frame" for Rviz 
the "frame_id" of the original point cloud.

Please, let me know if this solves your problem.

Best regards,

--roberto

**Comment by Raffa87** [comment]
It works! Thanks!
